# Generated by Django 5.0.3 on 2024-03-21 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Login_Info',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Staff_Registration',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('designation', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Registration',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('designation', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('course', models.CharField(max_length=5)),
                ('passkey', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Commend',
            fields=[
                ('command_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('command', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=10)),
                ('answer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ed_Core.answer')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('quesiton', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=10)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ed_Core.login_info')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ed_Core.question'),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('reply_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('reply', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=10)),
                ('command_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ed_Core.commend')),
            ],
        ),
        migrations.CreateModel(
            name='Saved_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('qusetion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ed_Core.question')),
            ],
        ),
    ]
