# Generated by Django 5.0.3 on 2024-03-21 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ed_Core', '0002_alter_answer_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commend',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ed_Core.login_info'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ed_Core.login_info'),
        ),
        migrations.AlterField(
            model_name='saved_items',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ed_Core.login_info'),
        ),
    ]
