# Generated by Django 5.0.3 on 2024-03-26 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ed_Core', '0003_alter_commend_username_alter_reply_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
