# Generated by Django 5.0.3 on 2024-03-26 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ed_Core', '0004_question_date_alter_question_question_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ed_Core.student_registration'),
        ),
    ]
