# Generated by Django 5.0.3 on 2024-03-26 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ed_Core', '0005_alter_question_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='commend',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='reply',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='answer',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ed_Core.staff_registration'),
        ),
        migrations.AlterField(
            model_name='commend',
            name='command_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply_id',
            field=models.CharField(max_length=50),
        ),
    ]
