# Generated by Django 5.0.3 on 2024-03-29 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ed_Core', '0007_remove_answer_answer_id_remove_answer_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saved_items',
            old_name='qusetion_id',
            new_name='question_id',
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ans', to='Ed_Core.question'),
        ),
        migrations.AlterField(
            model_name='commend',
            name='answer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms', to='Ed_Core.answer'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='command_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rpls', to='Ed_Core.commend'),
        ),
    ]
