# Generated by Django 5.0.3 on 2024-03-29 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ed_Core', '0008_rename_qusetion_id_saved_items_question_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_id',
        ),
        migrations.AddField(
            model_name='question',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ed_Core.question'),
        ),
        migrations.AlterField(
            model_name='commend',
            name='answer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ed_Core.answer'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='command_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ed_Core.commend'),
        ),
    ]
