# Generated by Django 5.0.3 on 2024-03-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ed_Core', '0009_remove_question_question_id_question_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='id',
        ),
        migrations.AddField(
            model_name='question',
            name='question_id',
            field=models.BigAutoField(default=11, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
