# Generated by Django 5.0.3 on 2024-03-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ed_Core', '0010_remove_question_id_question_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commend',
            name='command',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply',
            field=models.CharField(max_length=500),
        ),
    ]
