# Generated by Django 5.0.3 on 2024-03-31 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ed_Core', '0011_alter_commend_command_alter_reply_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff_registration',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='student_registration',
            name='designation',
        ),
    ]
