# Generated by Django 5.0.3 on 2024-04-01 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ed_Core', '0012_remove_staff_registration_designation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff_registration',
            old_name='department',
            new_name='course',
        ),
    ]
